version: '3.8'

services:

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db

  app:
    build: .
    container_name: financial_analyzer_app
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

volumes:
  dbdata6:
